---
version: 2.1
orbs: null
jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 1c:96:c3:7b:5a:95:62:78:96:7f:e6:a7:e7:ab:f4:70
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook main-remote.yml -i inventory
workflows:
  myWorkflow:
    jobs:
      - configure_infrastructure